export default {
	ON_CREATED: 'ON_CREATED',
	ON_SUBMIT: 'ON_SUBMIT',
	ON_SUBMITED: 'ON_SUBMITTED',
	ON_PROGRESS: 'ON_PROGRESS',
	ON_TOTAL_PROGRESS: 'ON_TOTAL_PROGRESS',
	ON_UPLOAD: 'ON_UPLOAD',
	ON_UPLOAD_CHUNK: 'ON_UPLOAD_CHUNK',
	ON_UPLOAD_CHUNK_SUCCESS: 'ON_UPLOAD_CHUNK_SUCCESS',
	ON_SUBMIT_DELETE: 'ON_SUBMIT_DELETE',
	ON_STATUS_CHANGE: 'ON_STATUS_CHANGE',
	ON_RESUME: 'ON_RESUME',
	ON_SESSION_REQUEST_COMPLETE: 'ON_SESSION_REQUEST_COMPLETE',
	ON_MANUAL_RETRY: 'ON_MANUAL_RETRY',
	ON_ERROR: 'ON_ERROR',
	ON_DELETE: 'ON_DELETE',
	ON_DELETE_COMPLETE: 'ON_DELETE_COMPLETE',
	ON_COMPLETE: 'ON_COMPLETE',
	ON_ALL_COMPLETE: 'ON_ALL_COMPLETE',
	ON_CANCEL: 'ON_CANCEL',
	ON_AUTO_RETRY: 'ON_AUTO_RETRY'
}

//https://docs.fineuploader.com/branch/master/api/events.html